apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: microservice-architecture
build:
  artifacts:
    - image: ghcr.io/msrumon/service1
      context: service1
    - image: ghcr.io/msrumon/service2
      context: service2
    - image: ghcr.io/msrumon/service3
      context: service3
    - image: ghcr.io/msrumon/web
      context: web
deploy:
  kubectl:
    manifests:
      - k8s/development/volumes.yaml
      - k8s/common/*
      - k8s/development/networks.yaml
