apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: microservice-template
build:
  artifacts:
    - image: ghcr.io/msrumon/service-1
      context: service-1
    - image: ghcr.io/msrumon/service-2
      context: service-2
    - image: ghcr.io/msrumon/service-3
      context: service-3
deploy:
  kubectl:
    manifests:
      - k8s/development/*
      - k8s/common/*
