apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: tests
build:
  artifacts:
  - image: ghcr.io/msrumon/service-1:master
    context: service-1
    docker:
      dockerfile: Dockerfile
  - image: ghcr.io/msrumon/service-2:master
    context: service-2
    docker:
      dockerfile: Dockerfile
  - image: ghcr.io/msrumon/service-3:master
    context: service-3
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/nats.yaml
    - k8s/service-1.yaml
    - k8s/service-2.yaml
    - k8s/service-3.yaml
