apiVersion: v1
kind: Service
metadata:
  name: service-service-1
spec:
  selector:
    app: service-1
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service-1
spec:
  selector:
    matchLabels:
      app: service-1
  template:
    metadata:
      labels:
        app: service-1
    spec:
      containers:
        - name: service-1
          image: ghcr.io/wereReallyGood/service-1:latest
          resources:
            limits:
              cpu: '2'
              memory: 256Mi
