apiVersion: v1
kind: Service
metadata:
  name: service-service-1-app
spec:
  selector:
    app: service-1-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service-1-app
spec:
  selector:
    matchLabels:
      app: service-1-app
  template:
    metadata:
      labels:
        app: service-1-app
    spec:
      containers:
        - name: service-1-app
          image: ghcr.io/msrumon/service-1:master
          resources:
            limits:
              cpu: '2'
              memory: 256Mi
