apiVersion: v1
kind: Service
metadata:
  name: service-service-2
spec:
  selector:
    app: service-2
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service-2
spec:
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
    spec:
      containers:
        - name: service-2
          image: ghcr.io/msrumon/service-2:master
          resources:
            limits:
              cpu: '2'
              memory: 256Mi
