apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-hostpath-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nats-data-pv
spec:
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hostpath-storage
  hostPath:
    path: /mnt/wsl/nats-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-data-pvc
spec:
  volumeName: nats-data-pv
  resources:
    requests:
      storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hostpath-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nats-scripts-pv
spec:
  capacity:
    storage: 5Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hostpath-storage
  hostPath:
    path: /mnt/wsl/nats-scripts
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-scripts-pvc
spec:
  volumeName: nats-scripts-pv
  resources:
    requests:
      storage: 5Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hostpath-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: service-1-pv
spec:
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hostpath-storage
  hostPath:
    path: /mnt/wsl/service-1
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-1-pvc
spec:
  volumeName: service-1-pv
  resources:
    requests:
      storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hostpath-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: service-2-pv
spec:
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hostpath-storage
  hostPath:
    path: /mnt/wsl/service-2
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-2-pvc
spec:
  volumeName: service-2-pv
  resources:
    requests:
      storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hostpath-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: service-3-pv
spec:
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hostpath-storage
  hostPath:
    path: /mnt/wsl/service-3
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-3-pvc
spec:
  volumeName: service-3-pv
  resources:
    requests:
      storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hostpath-storage
