apiVersion: v1
kind: Service
metadata:
  name: service-nats-db
spec:
  selector:
    app: nats-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nats-db
spec:
  selector:
    matchLabels:
      app: nats-db
  template:
    metadata:
      labels:
        app: nats-db
    spec:
      containers:
        - name: nats-db
          image: postgres:latest
          envFrom:
            - secretRef:
                name: nats-db-secrets
          volumeMounts:
            - name: nats-data-volume
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
      volumes:
        - name: nats-data-volume
          persistentVolumeClaim:
            claimName: nats-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nats-service
spec:
  selector:
    app: nats-server
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nats-server
spec:
  selector:
    matchLabels:
      app: nats-server
  template:
    metadata:
      labels:
        app: nats-server
    spec:
      containers:
        - name: nats-server
          image: nats-streaming:latest
          envFrom:
            - secretRef:
                name: nats-db-secrets
          args:
            - '--port'
            - '4222'
            - '-http_port'
            - '8222'
            - '--hb_interval'
            - '1m'
            - '--hb_timeout'
            - '5s'
            - '--hb_fail_count'
            - '3'
            - '--stan_debug'
            # - '--store'
            # - 'SQL'
            # - '--sql_driver'
            # - 'postgres'
            # - '--sql_source'
            # - 'host=service-nats-db port=5432 user=$(POSTGRES_USER) password=$(POSTGRES_PASSWORD) dbname=$(POSTGRES_DB) sslmode=disable'
            # - '--sql_max_open_conns'
            # - '3'
            # - '--sql_bulk_insert_limit'
            # - '10'
            - '--cluster_id'
            - 'msrumon'
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 750m
              memory: 256Mi
