apiVersion: v1
kind: Service
metadata:
  name: service-service2-db
spec:
  selector:
    app: service2-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service2-db
spec:
  selector:
    matchLabels:
      app: service2-db
  template:
    metadata:
      labels:
        app: service2-db
    spec:
      containers:
        - name: service2-db
          image: mongo:latest
          volumeMounts:
            - name: service2-data-volume
              mountPath: /data/db
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
      volumes:
        - name: service2-data-volume
          persistentVolumeClaim:
            claimName: service2-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: service-service2-app
spec:
  selector:
    app: service2-app
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service2-app
spec:
  selector:
    matchLabels:
      app: service2-app
  template:
    metadata:
      labels:
        app: service2-app
    spec:
      containers:
        - name: service2-app
          image: ghcr.io/msrumon/service2:master
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
