apiVersion: v1
kind: Service
metadata:
  name: service-service3-db
spec:
  selector:
    app: service3-db
  ports:
    - name: service3-db
      port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service3-db
spec:
  selector:
    matchLabels:
      app: service3-db
  template:
    metadata:
      labels:
        app: service3-db
    spec:
      containers:
        - name: service3-db
          image: mongo:latest
          volumeMounts:
            - name: service3-data-volume
              mountPath: /data/db
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          # livenessProbe:
          #   exec:
          #     command:
          #       - 'mongosh'
          #       - '--eval'
          #       - 'db.adminCommand("ping")'
      volumes:
        - name: service3-data-volume
          persistentVolumeClaim:
            claimName: service3-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: service-service3-app
spec:
  selector:
    app: service3-app
  ports:
    - name: service3-app
      port: 3003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service3-app
spec:
  selector:
    matchLabels:
      app: service3-app
  template:
    metadata:
      labels:
        app: service3-app
    spec:
      containers:
        - name: service3-app
          image: ghcr.io/msrumon/service3:master
          env:
            - name: RABBITMQ_URI
              value: amqp://service-rabbitmq:5672
            - name: MONGODB_URI
              value: mongodb://service-service3-db:27017/service3
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /api/service3/healthiness
              port: 3003
