apiVersion: v1
kind: Service
metadata:
  name: service-service2-db
spec:
  selector:
    app: service2-db
  ports:
    - name: service2-db
      port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service2-db
spec:
  selector:
    matchLabels:
      app: service2-db
  template:
    metadata:
      labels:
        app: service2-db
    spec:
      containers:
        - name: service2-db
          image: mongo:latest
          volumeMounts:
            - name: service2-data-volume
              mountPath: /data/db
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          # livenessProbe:
          #   exec:
          #     command:
          #       - 'mongosh'
          #       - '--eval'
          #       - 'db.adminCommand("ping")'
      volumes:
        - name: service2-data-volume
          persistentVolumeClaim:
            claimName: service2-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: service-service2-app
spec:
  selector:
    app: service2-app
  ports:
    - name: service2-app
      port: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service2-app
spec:
  selector:
    matchLabels:
      app: service2-app
  template:
    metadata:
      labels:
        app: service2-app
    spec:
      containers:
        - name: service2-app
          image: ghcr.io/msrumon/service2:master
          env:
            - name: RABBITMQ_URI
              value: amqp://service-rabbitmq:5672
            - name: MONGODB_URI
              value: mongodb://service-service2-db:27017/service2
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          # livenessProbe:
          #   httpGet:
          #     path: /api/service2/healthiness
          #     port: 3002
