apiVersion: v1
kind: Service
metadata:
  name: service-service-2-app
spec:
  selector:
    app: service-2-app
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service-2-app
spec:
  selector:
    matchLabels:
      app: service-2-app
  template:
    metadata:
      labels:
        app: service-2-app
    spec:
      containers:
        - name: service-2-app
          image: ghcr.io/msrumon/service-2:master
          resources:
            limits:
              cpu: '4'
              memory: 1Gi
