# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: service-1-db-pv
# spec:
#   capacity:
#     storage: 250Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#     - ReadOnlyMany
#     - ReadWriteMany
#   storageClassName: do-block-storage
#   csi:
#     driver: dobs.csi.digitalocean.com
#     fsType: ext4
#     volumeHandle: ''
#     volumeAttributes:
#       com.digitalocean.csi/noformat: 'true'
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: service-2-db-pv
# spec:
#   capacity:
#     storage: 250Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#     - ReadOnlyMany
#     - ReadWriteMany
#   storageClassName: do-block-storage
#   csi:
#     driver: dobs.csi.digitalocean.com
#     fsType: ext4
#     volumeHandle: ''
#     volumeAttributes:
#       com.digitalocean.csi/noformat: 'true'
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: service-3-db-pv
# spec:
#   capacity:
#     storage: 250Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#     - ReadOnlyMany
#     - ReadWriteMany
#   storageClassName: do-block-storage
#   csi:
#     driver: dobs.csi.digitalocean.com
#     fsType: ext4
#     volumeHandle: ''
#     volumeAttributes:
#       com.digitalocean.csi/noformat: 'true'
