# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: service-1-db-pv
# spec:
#   capacity:
#     storage: 50Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
#   storageClassName: do-block-storage
#   csi:
#     driver: dobs.csi.digitalocean.com
#     fsType: ext4
#     volumeHandle: ''
#     volumeAttributes:
#       com.digitalocean.csi/noformat: 'true'
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: service-1-db-pvc
# spec:
#   volumeName: service-1-db-pv
#   resources:
#     requests:
#       storage: 50Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
#   storageClassName: do-block-storage
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: service-2-db-pv
# spec:
#   capacity:
#     storage: 50Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
#   storageClassName: do-block-storage
#   csi:
#     driver: dobs.csi.digitalocean.com
#     fsType: ext4
#     volumeHandle: ''
#     volumeAttributes:
#       com.digitalocean.csi/noformat: 'true'
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: service-2-db-pvc
# spec:
#   volumeName: service-2-db-pv
#   resources:
#     requests:
#       storage: 50Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
#   storageClassName: do-block-storage
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: service-3-db-pv
# spec:
#   capacity:
#     storage: 50Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
#   storageClassName: do-block-storage
#   csi:
#     driver: dobs.csi.digitalocean.com
#     fsType: ext4
#     volumeHandle: ''
#     volumeAttributes:
#       com.digitalocean.csi/noformat: 'true'
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: service-3-db-pvc
# spec:
#   volumeName: service-3-db-pv
#   resources:
#     requests:
#       storage: 50Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
#   storageClassName: do-block-storage
