name: CD of service-1

on:
  push:
    paths:
      - .github/**
      - service-1/**

jobs:
  build-push:
    name: Build the image and push to the container registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2
      - name: Login to the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata of the image
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository_owner }}/service-1
      - name: Build and push the image to the container registry
        uses: docker/build-push-action@v2
        with:
          context: service-1
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
  deploy:
    needs: build-push
    name: Update deployment of the Kubernetes cluster
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl binary
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save kubeconfig of DigitalOcean
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.KUBERNETES_CLUSTER_NAME }}
      - name: Rollout to latest image pulled from the container registry
        run: kubectl rollout restart deployment service-1
