name: CD of service-3

on:
  push:
    paths:
      - .github/**
      - service-3/**

jobs:
  build-push:
    name: Build the image and push it to the container registry
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   packages: write
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2
      - name: Login to the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata of the image
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository_owner }}/service-3
      - name: Build and push the image to the container registry
        uses: docker/build-push-action@v2
        with:
          context: service-3
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
