name: Deployment to Kubernetes cluster

on:
  push:
    branches:
      - master
    paths:
      - k8s/common/**
      - k8s/production/**

jobs:
  deploy:
    name: Deploy configs to the cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2
      - name: Set K8S context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.PROVIDER_KUBECONFIG_CONTENTS }}
          context: ${{ secrets.PROVIDER_KUBECONFIG_CONTEXT }}
      - name: Create secrets
        uses: azure/k8s-create-secret@v1
        with:
          secret-name: nats-db-secrets
          secret-type: Opaque
          arguments: ${{  secrets.SECRETS_NATS_DB }}
      - name: Setup Ingress controller
        run: kubectl apply -f ${{ secrets.PROVIDER_INGRESS_MANIFEST }}
      - name: Apply the manifests
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            k8s/production/*
            k8s/common/*
